### ISSUE TITLE
Can't delete Events once they're created

### ISSUE THREAD

**Issue by estensen** [scalableinternetservices/ucsb_class_scheduler#16]
**The Events are selectable, but there is no intuitive way to delete them.**
Solution 1: Add popup when event is selected with options like "remove event"
Solution 2: Add Edit button to batch edit events in list under the Calendar

<img width="600" alt="screenshot 2017-10-21 19 23 36" src="https://user-images.githubusercontent.com/9142800/31857513-5b18d7b6-b695-11e7-8fed-330ce300d03a.png">

**Comment by evenskari** [comment]
Solution 3: Make x appear in top right corner when mouse hovers over event. Click --> remove event

**Comment by estensen** [comment]
Too much work to edit the components
